### ISSUE TITLE
problem reading multiple files

### ISSUE THREAD

**Issue by slhogle** [snayfach/MicrobeCensus#22]
Hi thanks for the useful software.

Everything works fine when running with a single read file, but when trying to pass multiple files and/or paired read files I get errors like:

`The following error was encountered when parsing sequence#2 in the input file:
I/O operation on closed file`

The weird thing is that the sequence # changes anywhere from 2 to 12. The other weird thing is that I got it to run once on test paired reads where I modified the header somehow but I can't remember what I did :anguished:

python version 2.7.14
MicrobeCensus version 1.1

best,
-shane

on my machine I can get a reproducible error using the two files:

test_1.fq
@NS500496_94_HCKNKBGXX:1:11101:14811:4036#GGACTCATAGAG/1
TTCGTAACCGATGTGAAGATCAGTTGCGGCACCAGAATAGTCTCCATCTGGATAAGAGATATTGCTCTCAACATTCACATATGGACCAGCAAAAGCTGCACCAGCGAGTAGGAATGGAGATGCTGCAACAGCAGCGATTGTTGATTTGAT
+
AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEE<EEAEEEEEEEEEEEEEEEEEEEEEEEEEAE
@NS500496_94_HCKNKBGXX:1:11101:15952:6689#GGACTCATAGAG/1
CAGTAAGACCAGTGCCAGTACCCCTGACATTAGTAGTAGCTACATCAGTTCCATTAGCAACATCAATGAGTACTTGGTTCCTTAGAATCCTAAGATTAGTAAAGTTCTCAATAGAGTCAGCAGGTACATCAAAGGTGGTAGTTCTATTGG
+
AAAAAEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEA
@NS500496_94_HCKNKBGXX:1:11101:12994:17022#GGACTCATAGAG/1
GCCGATGTTGAGTGGTTTTTATATACAAGTTCAGTTGGAGTATATCATCCAGCAGAAGTATTTAAAGAAGACGATGTGTGGAAAACATTTCCATCTGAACACGATTGGGAAGCAGGTTGGGCTAAAAGGATTGGTGAAATGAATGTTCAA
+
AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

test_2.fq
@NS500496_94_HCKNKBGXX:1:11101:14811:4036#GGACTCATAGAG/2
GCACACACCTAGTGTGACAGTTGTATAAATAACTTCATACAAAGGACTCGAAAGAATCGTAACCCTGCGTTGATGTAAACGGTTCCCCATGTCGGGGGAATTATCATCCGCAAGGGATTTTTTATTCTTGCGAGATACTTAACAAAC
+
AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEEEE<EEEEE<EEEEEEEEEEEEEEEA<AAEEEA
@NS500496_94_HCKNKBGXX:1:11101:15952:6689#GGACTCATAGAG/2
ATATCATGTCATTATGCGTGACACTTATTATGCTGTCACACGTATTGATGATGAGAATAAGATCCTTGCATTTGATATTAAGGAGACAGAAAACACTGCTCTAATTAATAATGACTATAGGGTTCACCTTGACAACCGTGTTAATATCGA
+
AAAAAEEEEEEEEEEEEEEE/EEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEAAEEEEE<EEEEEEEEEEEEEEE<EE/<EAEEEEEEEAEEEAEEEEEEEEEEEEEEEEEEEEAEAEEEEEE<<EAEEEAEEEEEEEA
@NS500496_94_HCKNKBGXX:1:11101:12994:17022#GGACTCATAGAG/2
CCACACTTCTAATTTATCATTATCTACAGCTTTTTTAATCAATGATGGTATAACCATTGACCACTTACCAAAGTCATCATCTATCCCATATACATTAGCAGGTCTAACAATTGAACAACAATTCCAATTGTGTTCTTTCATATAAGCTT
+
AAAAAEEEEEEE/EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEAEEEEEEEEEEEEEEAEEEEEEEE<<EEEEEAEEE/EEEEAEEEEEEEEEEEEEEE/AEEEEA<E<AEAEEEEEE/EEEEEEEEEEEE

**Comment by hansenzoe** [comment]
I am having the same issue as @slhogle as well. I have a series of paired-end FASTQ files that I am using as input, and I am actually able to process multiple samples at a time, but I receive this error for a subset of those samples: 

'The following error was encountered when parsing sequence#6 in the input file:
I/O operation on closed file.'

I am using Python 3.6.4 and MicrobeCensus 1.1.0. I am relatively new to bioinformatics, too, and so any help or insight as to why this might be happening would be greatly appreciated! Thank you!

**Comment by snayfach** [comment]
The issue should be fixed now, but please let me know if it isn't

**Comment by slhogle** [comment]
thanks can confirm issue is fixed!

-shane

**Comment by ZoeHansen** [comment]
@snayfach I am still receiving this issue: 

```
====Estimating Average Genome Size====
Sampling & trimming reads...

The following error was encountered when parsing sequence#6 in the input file:
I/O operation on closed file.
```
Could this simply be an issue on my end? I haven't had issues with my gzipped FASTQ paired-end files when running other software, but perhaps there is a compatibility issue? I will keep troubleshooting. 

Thank you for trying to fix this!

**Comment by snayfach** [comment]
I think you need to pull the latest version of the code using `git clone https://github.com/snayfach/MicrobeCensus`

**Comment by ZoeHansen** [comment]
@snayfach Thank you! I've pulled the latest version, and am now getting an indendation/tabs/spaces error when running the microbe_census.py script:
```
Traceback (most recent call last):
  File "/......../MicrobeCensus/microbe_census/microbe_census.py", line 335
    read_id, dups, too_short, low_qual = 0, 0, 0, 0
                                                                          ^
TabError: inconsistent use of tabs and spaces in indentation
```
Any help would be greatly appreciated!

**Comment by snayfach** [comment]
Can you please try again?

**Comment by ZoeHansen** [comment]
@snayfach Yes, it worked! Even for those problem files from before! In order to get it to run, though, I had to make a slight modification in response to this error:
```
Traceback (most recent call last):
  File "/.../MicrobeCensus/microbe_census/microbe_census.py", line 339
    print seqfile
                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print seqfile)?
```
Other than that, everything ran smoothly. Thank you VERY much for your time and help in fixing these issues! I (and others) really appreciate it!

**Comment by snayfach** [comment]
Thanks - I fixed that too
